[project]
name = "test-pathwidth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "graph-families",
    "milp-separation",
    "separation",
]

[tool.uv.sources]
graph-families = { git = "https://github.com/algebravic/graph_families.git" }
separation = { git = "https://github.com/algebravic/separation.git" }
milp-separation = { git = "https://github.com/algebravic/milp_separation.git" }

[project.scripts]
solve = "test_pathwidth.run:run_pathwidth"

[build-system]
requires = ["uv_build>=0.11.13,<0.12"]
build-backend = "uv_build"
